name: TypeScript Compile Work

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Telefondan manuel tetiklemek istersen buton açar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Derleme Islemi
        run: |
          npm install
          npx tsc || true

      - name: JS Dosyalarini Paketle
        uses: actions/upload-artifact@v4
        with:
          name: hosting-hazir-proje
          path: .
